name: Project
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: sudo apt install python3
            - name: Test code
              run: python3 ./src/test.py
    build:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Get Code
          uses: actions/checkout@v4
        - name: Build Image
          uses: ./.github/actions/build 
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Get Code
          uses: actions/checkout@v4
        - name: Download Image Artifact
          uses: actions/download-artifact@v3
        - name: Load Image
          run: docker load -i image/image.tar
          shell: bash
        - name: Deploy Image
          uses: ./.github/actions/deploy
        - name: See Images
          run: minikube kubectl get pods
