name: Project
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                sudo apt install python3
                sudo apt install python3-pip
                pip install re
                pip install collections
                pip install os
            - name: Run script
              run: python3 main.py
            - name: Test script
              run: python3 test.py
                
