name: Project
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: sudo apt install python3
            - name: Test code
              run: python3 ./src/test.py
    build:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Build Image
          uses: ./.github/actions/build
        - name: Show Images
          run: minikube image ls
    deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Deploy Image
          uses: ./.github/actions/deploy
        - name: See Images
          run: minikube kubectl get pods
